### ISSUE TITLE
Feedback from second course delivery of lesson 1

### ISSUE THREAD

**Issue by mwoodbri** [ImperialCollegeLondon/grad_school_software_engineering_course#13]
This feedback is based on delivery of lesson 1 on 11th March.

Instuctor: @mdavezac 
Helpers: @mwoodbri and @AdrianDAlessandro 

**See also #10 for remaining unresolved comments from first cohort.**

# Instructor/helper feedback on session
* Doing tooling up-front made it much easier for people to focus on the remaining content

# Technical Issues Encountered
* conda interaction with VS Code (in particular Code terminal). Main problem here was that the Software Hub seems to set up conda so that it works in the VS terminal, but this doesn't typically seem to be the case with self-installed version(?). Hence confusion when it work for the instructor but not for them.
* Still issues with users creating project folder on network drive rather than C: 

# Positive Attendee feedback
* Good hands-on preparation & introduction of linters and formatters
* Good explanation of concepts and debugging
* Really enjoyed finding out about tools (esp. environments)
* Good level of content
* Useful, implementable advice
* Sufficient demonstrators
* Informative class materials
* Good structure
* It's good but student need more preparation to attend the class
* Website and resources are useful with good examples
* Good class: well-structured materials
* Good examples

# Negative Attendee feedback
* Too basic even for someone from other discipline (not computer scientist)
* Better to ask students to install necessary softwares & setups in advance
* The course was a bit slow at times (but I guess that's to be expected when you have people of diff. abilities)
* Examples geared towards more towards numerical data analysis would be useful
* Webpage order of material is not the same as instructor
* Design shorter exercises, or select less exercises to complete & review them. Particularly in part 2.
* More precise steps
* Some more info given prior to session on how to set up e.g. list of terms with definitions (shell, environment, IDE etc). Would save time in session.

# Suggestions from instructor/helpers
* TODO

**Comment by AdrianDAlessandro** [comment]
- Content and online material are quite good
- Helpful to explain the layout/plan for the next two hours in more detail at the beginning. If nothing else, this will give the students confidence we are well-prepared and have a plan.
- Make sure students are aware of how to use the stickies

## Data Structures and Structuring Code sections
- I think the information in these sections is very good, and very clear.
- The examples are a bit unclear, it's non-obvious what is being asked of the students. Given the limited time, some **code template** to get students started could be useful.

## Tools sections
- This should be streamlined and simplified
- I think separating the "how to setup" and the "why are they useful" would help. I think students were missing the explanations of utility, and the examples, while trying to get VS Code to work. Probably explain the reasons why they're all useful _first_, then go through setup.

I suggest making the step-by-step of the tools setup more clear and all together (in the one episode), ie:

1. Open VS Code
2. Install Python Extension
3. Create folder for the course (in C: drive!) and open in VS Code
4. Create conda environment
5. Select Python interpreter to match the Conda env
6. Enable formatters
7. Enable linters

Then, after making sure most students have done these steps, get them to check everything has worked by doing the examples

**Comment by mwoodbri** [comment]
Comments from John Pinney:

> Worth thinking about the implicit prerequisites for your course. e.g. is it essential that students have an understanding of python? object-oriented coding? exceptions? It may be difficult to cover all situations because students have such a diversity of coding backgrounds, but is there anything you can do that would help e.g. a competent R or MATLAB user with no python experience get more from this course?
>
> The "tools" material is important practical information but doesn't lend itself easily to exercises, so there was a lot of time in the first session where we were waiting to move on. I think the three sections (virtual env / code formatters / linters) could be simplified and combined into a single "workspace setup" section, so that everyone gets to install just one version of each tool and we can see them working during exercises later on. This should also free up some time to look at other things.
>
> Need to signpost clearly when moving between the different web pages and within VSCode. I find that it's really easy to get lost with the SwC format because there are so many pages to deal with and so much text on each page.

**Comment by dandavies99** [comment]
@AdrianDAlessandro - do you think we can consider this issue closed now that there have been several iterations of the course in the three years since?

**Comment by AdrianDAlessandro** [comment]
No actionable items and course has changed significantly since this was opened
