### ISSUE TITLE
pin python version

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/grad_school_software_engineering_course#23]
The python version should be pinned to avoid problems in VS code relating to Python 3.10, which were encountered in the latest iteration of the course. 

Currently, `python==3.8` is listed as a dependency in environment.yaml (in [code/course.zip](https://github.com/ImperialCollegeLondon/grad_school_software_engineering_course/blob/3e950a4765c353db48a84ebbf826b8fee7cb656d/code/course.zip)) but `python>=3.8` is listed in the instructions of [episode 1](https://imperialcollegelondon.github.io/grad_school_software_engineering_course/l1-01-tools-I/index.html).

- These should both be either `==3.8` or `==3.9` for consistency. 
- @cc-a - Is there anywhere else in the repository where a python version should is specified?

**Comment by dandavies99** [comment]
New branch [here](https://github.com/ImperialCollegeLondon/grad_school_software_engineering_course/tree/pin-python-version).

**Comment by cc-a** [comment]
Thanks @dandavies99
