### ISSUE TITLE
Implement feedback form 2022 evaluation

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/grad_school_software_engineering_course#27]
The following is a list of issues to tackle in response to the feedback form the 2022 evaluation. If you can work on any of them, open a specific issue for it and assign yourself:

- [x] In answer to “I am better able to understand how and where to access support from the Research Computing Service at Imperial College”, most attendees were a bit puzzled -> We should give a short introduction of our team, webpage and resources should better inform students on this topic.
- [x] The lesson on [Design Patterns](https://imperialcollegelondon.github.io/grad_school_software_engineering_course/l1-06-design_patterns/index.html) is interesting but never delivered -> Move to an appendix and remove it from the main workflow of the course to avoid distraction and cognitive burden.
- [x] The `Setup` section is always an issue, specially with VSCode + Conda + Different OS -> Review the instructions and make sure they are up-to-date and work on different OS and Python>=3.9.
- [x] We need to review the time allocated to the different sections of the course, giving more hands-on activities in the first part and reducing the time for the second one -> This might imply reducing or removing some content, but overall it will be more shifting times.

**Comment by AdrianDAlessandro** [comment]
> * [ ]  In answer to “I am better able to understand how and where to access support from the Research Computing Service at Imperial College”, most attendees were a bit puzzled -> We should give a short introduction of our team, webpage and resources should better inform students on this topic.

The [About](https://imperialcollegelondon.github.io/grad_school_software_engineering_course/about/index.html) section contains this detail. Should we move that to the index page, or maybe just need to remember to open with a little bit of an "About us" section?

> * [ ]  The `Setup` section is always an issue, specially with VSCode + Conda + Different OS -> Review the instructions and make sure they are up-to-date and work on different OS and Python>=3.9.

This section simply provides links to the installation pages for anaconda, miniconda, and VSCode, which each have their own details for different OS etc. I will include a note to update to recent versions instead.

**Comment by dalonsoa** [comment]
> > * [ ]   In answer to “I am better able to understand how and where to access support from the Research Computing Service at Imperial College”, most attendees were a bit puzzled -> We should give a short introduction of our team, webpage and resources should better inform students on this topic.
> 
> The [About](https://imperialcollegelondon.github.io/grad_school_software_engineering_course/about/index.html) section contains this detail. Should we move that to the index page, or maybe just need to remember to open with a little bit of an "About us" section?

It is more about the delivery of the lesson itself, yes. Adding it to the index will highlight that and make it more clear, but if we can give a 3 min-long pitch about the RSE team at the beginning, that will be helpful.

**Comment by AdrianDAlessandro** [comment]
Okay, I have addressed this in #28

**Comment by dandavies99** [comment]
It looks like everything has been ticked off of the initial checklist ✅ 
Can we consider all tasks on this issue completed @dalonsoa @AdrianDAlessandro?

**Comment by dalonsoa** [comment]
All looks good to me!
