### ISSUE TITLE
Generate `course.zip` via CI pipeline -> Link ZIP file

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/grad_school_software_engineering_course#38]
Currently `course.zip` is included in the repo as a binary file, which makes its contents a bit opaque to git and GitHub. Alternatively, we could generate it (e.g. from a subfolder in the repo) as part of the CI pipeline which would make it somewhat easier to work with.

**Comment by dalonsoa** [comment]
Just link the Zip file in the dedicated repos created for using Codespaces, like this one:

https://github.com/ImperialCollegeLondon/grad_school_sw_engeneering_messy_code/archive/refs/heads/main.zip
