### ISSUE TITLE
Revise the Python tooling we present to students

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/grad_school_software_engineering_course#39]
At present, the course talks about `flake8` and `pylint`.

Given that we don't use `pylint` ourselves in our projects, I wonder how useful it is (it may be!). We could consider revising the tooling that we present to students to be more modern/useful (e.g. we could talk about `ruff`).

Part of the point of introducing `pylint` is to show students a second tool for its own sake, so if we were to remove it, we should probably talk about something else instead (`mypy`?).

**Comment by dalonsoa** [comment]
Let's move to ruff.
