### ISSUE TITLE
Add info on other languages linters, formatters, testing suites etc

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/grad_school_software_engineering_course#45]
The same way we do when explaining the data structures. Languages to support:

- R
- C++
- Fortran

**Comment by dalonsoa** [comment]
A cry for help! Could you advise on linters, formatters and testing suits for:

- @SaranjeetKaur - R
- @alexdewar and @jamesturner246 - C++
- @cc-a - Fortran

I'll compile whatever you tell me and put it in the right place in the lessons.

**Comment by jamesturner246** [comment]
What he said :smile:

**Comment by dalonsoa** [comment]
Let's also add info about package managers, or similar, to include in the page where we talk about conda, poetry, etc. 

I actually think I can answer most of the fortran stuff:

## Fortran

- **Package manager**: [Fortran Package Manager (FPM)](https://fpm.fortran-lang.org/)
- **Testing**: [Test-Drive](https://github.com/fortran-lang/test-drive). See the [Fibonacci series example](https://github.com/ImperialCollegeLondon/fortran_fibonacci) coded in Fortran. 
- **Linting**: Via compilers, like [gfortran](https://gcc.gnu.org/wiki/GFortran) or Intel’s [ifort and ifx](https://www.intel.com/content/www/us/en/developer/tools/oneapi/fortran-compiler.html)
- **Formatting**: [findent](https://github.com/gnikit/findent-pypi) and [fprettify](https://github.com/pseewald/fprettify)
- **VSCode integration**: [VSCode Modern Fortran extension](https://fortran-lang.github.io/vscode-fortran-support/), which integrates with the above linters and formatters and the Fortran Language Server [fortls](https://fortls.fortran-lang.org/).

**Comment by alexdewar** [comment]
For C++ you have `vcpkg` and Conan. You can also use the system package manager, but it's not a particularly portable approach.

**Comment by dalonsoa** [comment]
So, to summarize for C++:

## C++

- **Package manager**: [Conan](https://conan.io/) and [vcpkg](https://vcpkg.io/en/)
- **Testing**: [GoogleTest](https://google.github.io/googletest/), [Boost Test](https://www.boost.org/doc/libs/1_75_0/libs/test/doc/html/index.html) and [Catch 2](https://github.com/catchorg/Catch2). See [our C++ testing course using Google Test](https://imperialcollegelondon.github.io/unit_testing_Cpp/). 
- **Linting**: [clang-tidy](https://clang.llvm.org/extra/clang-tidy/) and [CppCheck](http://cppcheck.net/), although compilers can give lots of helpful linter-type warnings. For `gcc` and `clang`, it's a good idea to pass the `-Wall`, `-Wextra` and `-Wpedantic` flags to get extra ones.
- **Formatting**: [clang-format](https://clang.llvm.org/docs/ClangFormat.html)
- **VSCode integration**: [C/C++ VSCode extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools), including a [full tutorial](https://code.visualstudio.com/docs/languages/cpp) on how to set VSCode to work with C++.

**Comment by alexdewar** [comment]
LGTM. I've generally not bothered trying to make VS Code work for C++ on Windows though, because it's a bit of a pain and you can just use Visual Studio.

It seems like it's possible though: https://code.visualstudio.com/docs/cpp/config-msvc#_prerequisites

^^ @jamesturner246

**Comment by dalonsoa** [comment]
And for R, pending on @SaranjeetKaur 's seal of approval:

## R

- **Package manager**: [packrat](https://rstudio.github.io/packrat/) and [checkpoint](https://www.rdocumentation.org/packages/checkpoint/versions/1.0.2)
- **Testing**: [testthat](https://testthat.r-lib.org/)
- **Linting**: [lintr](https://lintr.r-lib.org/), with [RStudio integration](https://lintr.r-lib.org/articles/editors.html).
- **Formatting**: [styler](https://styler.r-lib.org/), with [RStudio integration](https://styler.r-lib.org/reference/styler_addins.html).
- **RStudio**: The linter and formatter both can be integrated with RStudio via RStudio Addins.

**Comment by dalonsoa** [comment]
> LGTM. I've generally not bothered trying to make VS Code work for C++ on Windows though, because it's a bit of a pain and you can just use Visual Studio.
> 
> It seems like it's possible though: https://code.visualstudio.com/docs/cpp/config-msvc#_prerequisites
> 
> ^^ @jamesturner246

Added as a comment.

**Comment by dalonsoa** [comment]
OK about pfUnit and fortran-linter.

About the last comment, in theory VSCode does it: https://fortran-lang.github.io/vscode-fortran-support/#linting

**Comment by dalonsoa** [comment]
The fortran-linter does not integrate with VSCode, which is obviously not a problem, but for many people might be a limitation.

**Comment by dalonsoa** [comment]
It's funny: `fortran` linters and formatters are written in `python`, while `python` linters and formatters are written in `rust`. Now, it should be that `rust` linters and formatters were written in `fortran`, to close the circle 😆

**Comment by cc-a** [comment]
> About the last comment, in theory VSCode does it: https://fortran-lang.github.io/vscode-fortran-support/#linting

Ah, good to know.

**Comment by SaranjeetKaur** [comment]
> And for R, pending on @SaranjeetKaur 's seal of approval:
> 
> ## R
> * **Package manager**: [packrat](https://rstudio.github.io/packrat/) and [checkpoint](https://www.rdocumentation.org/packages/checkpoint/versions/1.0.2)
> * **Testing**: [testthat](https://testthat.r-lib.org/)
> * **Linting**: [lintr](https://lintr.r-lib.org/), with [RStudio integration](https://lintr.r-lib.org/articles/editors.html).
> * **Formatting**: [styler](https://styler.r-lib.org/), with [RStudio integration](https://styler.r-lib.org/reference/styler_addins.html).
> * **RStudio**: The linter and formatter both can be integrated with RStudio via RStudio Addins.

These are all good!
